require("core.keymaps")
require("core.plugins")
require("core.pluginconfig.nvim-tree")
require("core.pluginconfig.dracula")
require("core.pluginconfig.treesitter")
require("core.pluginconfig.telescope")
require("core.pluginconfig.nvim-lspconfig")
